Edit msg@T.Text: Edit #{msg}
EditArticle: Edit an article
LoggedInAs name@T.Text: You are logged in as #{name}.
NotLoggedIn: You are not logged in.
Login: Login
Logout: Logout
DeleteArticle: DELETE
EditOn: Edit
PostArticle: Post a new article
Comments: Comment(s)
Preview: Preview
InvalidInput: Invalid inputs. Try it again.
AlreadyExists title@T.Text: The article "#{title}" already exists.
ArticlesForTag tag@T.Text: Articles tagged with "#{tag}"
Articles: Articles
