Edit msg@T.Text: Edit #{msg}
EditArticle: Edit an article
LoggedInAs name@T.Text: You are logged in as #{name}.
NotLoggedIn: You are not logged in.
Login: Login
Logout: Logout
DeleteArticle: DELETE
EditOn: Edit
PostArticle: Post a new article
Comments: Comment(s)
Preview: Preview
InvalidInput: Invalid inputs. Try it again.
AlreadyExists title@T.Text: The article "#{title}" already exists.
ArticlesForTag tag@T.Text: Articles tagged with "#{tag}"
Articles: Articles
LeaveComment: Leave a comment
Article: Article
Title: Title
Tags: Tags
CreatedDate: Created date
CreatedTime: Created time
Name: Name
Comment: Comment
DeleteComment: Delete Comments
DeleteTrackback: Delete Trackbacks
DeleteCommentTrackback: Delete Trackbacks and Comments
Tweet: Tweet
NoComments: No Comments
Trackbacks: Trackbacks
NoTrackbacks: No Trackbacks
Identifier: Identifier
NewComment: You have new comment
YouHaveNewCommentFor url@T.Text: You have new comment for: #{url}
Search: Search
