Default: &defaults
  user: Yablog
  password: Yablog
  host: localhost
  port: 27017
  connections: 5
  database: Yablog

Development:
  <<: *defaults

Test:
  database: Yablog_test
  <<: *defaults

Staging:
  database: Yablog_staging
  poolsize: 100
  <<: *defaults

Production:
  database: Yablog_production
  poolsize: 100
  <<: *defaults
